server {
    listen 80;
    server_name cetinkayavinc.com www.cetinkayavinc.com;

    location / {
        root /usr/share/nginx/html;
        include /etc/nginx/mime.types; # Bu satırın olduğundan emin olalım
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Eski tarayıcılar için cache'i zorla temizle
    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires 1d;
        add_header Cache-Control "public, no-transform";
    }
}
