server {
    listen 80;
    server_name cetinkayavinc.com www.cetinkayavinc.com;
    return 301 https://$host$request_uri; # HTTP'yi HTTPS'e zorla
}

server {
    listen 443 ssl;
    server_name cetinkayavinc.com www.cetinkayavinc.com;

    ssl_certificate /etc/letsencrypt/live/cetinkayavinc.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cetinkayavinc.com/privkey.pem;

    # Eski cihazlar için uyumluluk ayarları
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
